services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: shubham
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: devopsass1
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    container_name: backend
    build: ./backend/
    volumes:
      - shared_logs:/shared/logs
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: devopsass1
      DB_USER: shubham
      DB_PASSWORD: testpassword
    depends_on:
      - db


  frontend:
    container_name: frontend
    build: ./frontend/
    depends_on:
      - db
      - backend
    ports:
      - "8080:8080"

    environment:
      BACKEND_URL: http://backend:5000/api/data


  logger:
    container_name: logger
    build: ./logger/
    depends_on:
      - db
      - backend
    volumes:
      - shared_logs:/shared/logs

volumes:
  db_data:
  shared_logs: